spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bene_ai
    username: SEU_USUARIO
    password: SUA_SENHA

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true